name: pydamage_poster
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.1
  - altair=4.1.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow-cpp=4.0.0
  - astor=0.8.1
  - async_generator=1.10
  - attrs=21.2.0
  - aws-c-cal=0.5.7
  - aws-c-common=0.5.11
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.9.12
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - base58=2.1.0
  - black=21.5b0
  - bleach=3.3.0
  - blinker=1.4
  - boto3=1.17.72
  - botocore=1.20.72
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.2
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=8.0.0
  - cryptography=3.4.7
  - dataclasses=0.8
  - decorator=5.0.7
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.17
  - glog=0.5.0
  - grpc-cpp=1.37.1
  - idna=2.10
  - importlib-metadata=4.0.1
  - ipykernel=5.5.5
  - ipython=7.23.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=3.0.0
  - jmespath=0.10.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - krb5=1.19.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.1
  - libcxx=11.1.0
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libthrift=0.14.1
  - libtiff=4.2.0
  - libutf8proc=2.6.1
  - libwebp-base=1.2.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markupsafe=2.0.0
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mypy_extensions=0.4.3
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.3.0
  - numpy=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - orc=1.6.7
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.13
  - pandocfilters=1.4.3
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - pathspec=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - protobuf=3.16.0
  - ptyprocess=0.7.0
  - pyarrow=4.0.0
  - pycparser=2.20
  - pydeck=0.6.2
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysam=0.16.0.1
  - pysocks=1.7.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - re2=2021.04.01
  - readline=8.1
  - regex=2021.4.4
  - requests=2.25.1
  - s3transfer=0.4.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.8
  - sqlite=3.35.5
  - streamlit=0.81.1
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.3
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - tzlocal=2.1
  - urllib3=1.26.4
  - validators=0.18.2
  - watchdog=2.1.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - biopython==1.78
    - cycler==0.10.0
    - joypy==0.2.5
    - kiwisolver==1.3.1
    - kneed==0.7.0
    - matplotlib==3.4.2
    - patsy==0.5.1
    - plotly==4.14.3
    - git+ssh://git@github.com/maxibor/pydamage.git@dev
    - retrying==1.3.3
    - scipy==1.6.3
    - statsmodels==0.12.2
    - tqdm==4.60.0