name: pydamage_poster
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click=8.0.0
  - numpy=1.20.2
  - pandas=1.2.4
  - pip=21.1.1
  - pysam=0.16.0.1
  - python=3.9.4
  - streamlit=0.81.1
  - pip:
    - biopython==1.78
    - cycler==0.10.0
    - joypy==0.2.5
    - kiwisolver==1.3.1
    - kneed==0.7.0
    - matplotlib==3.4.2
    - patsy==0.5.1
    - plotly==4.14.3
    - git+https://git@github.com/maxibor/pydamage.git@dev
    - retrying==1.3.3
    - scipy==1.6.3
    - statsmodels==0.12.2
    - tqdm==4.60.0